version: "3.7"
services:
  app:
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
    command:
      - ./binary/main
    volumes:
      - .:/opt
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5532:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name:
      fifth_test_db

volumes:
  postgres_data: